-- 코드를 입력하세요
SELECT DATE_FORMAT(DATETIME, "%H"), COUNT(*)
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, "%H")>=9 AND DATE_FORMAT(DATETIME, "%H")<20
GROUP BY DATE_FORMAT(DATETIME, "%H")
ORDER BY DATE_FORMAT(DATETIME, "%H")
